import unreal

tools = unreal.AssetToolsHelpers.get_asset_tools()
material = unreal.EditorAssetLibrary.load_asset("/Game/Materials/M_PlayerShieldSphere")
if material is None:
    material = tools.create_asset("M_PlayerShieldSphere", "/Game/Materials", unreal.Material, unreal.MaterialFactoryNew())
unreal.MaterialEditingLibrary.delete_all_material_expressions(material)
material.set_editor_property("blend_mode", unreal.BlendMode.BLEND_TRANSLUCENT)
material.set_editor_property("shading_model", unreal.MaterialShadingModel.MSM_UNLIT)
material.set_editor_property("two_sided", True)

color = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionVectorParameter, -800, -160)
color.set_editor_property("parameter_name", "EffectColor")
color.set_editor_property("default_value", unreal.LinearColor(0.0, 0.12, 0.8, 0.1))
intensity = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionScalarParameter, -800, -20)
intensity.set_editor_property("parameter_name", "Intensity")
intensity.set_editor_property("default_value", 2.0)
fresnel = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionFresnel, -800, 160)
glow = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionMultiply, -500, -100)
unreal.MaterialEditingLibrary.connect_material_expressions(color, "", glow, "A")
unreal.MaterialEditingLibrary.connect_material_expressions(intensity, "", glow, "B")
rim = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionMultiply, -250, -30)
unreal.MaterialEditingLibrary.connect_material_expressions(glow, "", rim, "A")
unreal.MaterialEditingLibrary.connect_material_expressions(fresnel, "", rim, "B")
unreal.MaterialEditingLibrary.connect_material_property(rim, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
opacity = unreal.MaterialEditingLibrary.create_material_expression(material, unreal.MaterialExpressionMultiply, -250, 150)
opacity.set_editor_property("const_b", 0.22)
unreal.MaterialEditingLibrary.connect_material_expressions(fresnel, "", opacity, "A")
unreal.MaterialEditingLibrary.connect_material_property(opacity, "", unreal.MaterialProperty.MP_OPACITY)
unreal.MaterialEditingLibrary.recompile_material(material)
unreal.EditorAssetLibrary.save_loaded_asset(material, only_if_is_dirty=False)
unreal.log("Created original Zombie Zero sphere shield material")
